services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - otus-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - otus-network

networks:
  otus-network:
    driver: bridge

volumes:
  mongo_data:
