// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: agent.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentTasks  []*Task                `protobuf:"bytes,3,rep,name=current_tasks,json=currentTasks,proto3" json:"current_tasks,omitempty"`
	Metrics       *HostMetrics           `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AgentInfo) GetCurrentTasks() []*Task {
	if x != nil {
		return x.CurrentTasks
	}
	return nil
}

func (x *AgentInfo) GetMetrics() *HostMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetAgentByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentByIdRequest) Reset() {
	*x = GetAgentByIdRequest{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentByIdRequest) ProtoMessage() {}

func (x *GetAgentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAgentByIdRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgentByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentByIdResponse) Reset() {
	*x = GetAgentByIdResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentByIdResponse) ProtoMessage() {}

func (x *GetAgentByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAgentByIdResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentByIdResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetAllAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAgentsRequest) Reset() {
	*x = GetAllAgentsRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAgentsRequest) ProtoMessage() {}

func (x *GetAllAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAgentsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

type GetAllAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAgentsResponse) Reset() {
	*x = GetAllAgentsResponse{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAgentsResponse) ProtoMessage() {}

func (x *GetAllAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type PostAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAgentRequest) Reset() {
	*x = PostAgentRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAgentRequest) ProtoMessage() {}

func (x *PostAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAgentRequest.ProtoReflect.Descriptor instead.
func (*PostAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PostAgentRequest) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type PostAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAgentResponse) Reset() {
	*x = PostAgentResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAgentResponse) ProtoMessage() {}

func (x *PostAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAgentResponse.ProtoReflect.Descriptor instead.
func (*PostAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

type PutAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Agent         *AgentInfo             `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAgentRequest) Reset() {
	*x = PutAgentRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAgentRequest) ProtoMessage() {}

func (x *PutAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAgentRequest.ProtoReflect.Descriptor instead.
func (*PutAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PutAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutAgentRequest) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type PutAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAgentResponse) Reset() {
	*x = PutAgentResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAgentResponse) ProtoMessage() {}

func (x *PutAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAgentResponse.ProtoReflect.Descriptor instead.
func (*PutAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x03api\x1a\n" +
	"task.proto\x1a\rmetrics.proto\"\x9a\x01\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12.\n" +
	"\rcurrent_tasks\x18\x03 \x03(\v2\t.api.TaskR\fcurrentTasks\x12*\n" +
	"\ametrics\x18\x04 \x01(\v2\x10.api.HostMetricsR\ametrics\"%\n" +
	"\x13GetAgentByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x14GetAgentByIdResponse\x12$\n" +
	"\x05agent\x18\x01 \x01(\v2\x0e.api.AgentInfoR\x05agent\"\x15\n" +
	"\x13GetAllAgentsRequest\">\n" +
	"\x14GetAllAgentsResponse\x12&\n" +
	"\x06agents\x18\x01 \x03(\v2\x0e.api.AgentInfoR\x06agents\"8\n" +
	"\x10PostAgentRequest\x12$\n" +
	"\x05agent\x18\x01 \x01(\v2\x0e.api.AgentInfoR\x05agent\"\x13\n" +
	"\x11PostAgentResponse\"G\n" +
	"\x0fPutAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x05agent\x18\x02 \x01(\v2\x0e.api.AgentInfoR\x05agent\"\x12\n" +
	"\x10PutAgentResponse\"$\n" +
	"\x12DeleteAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteAgentResponse2\xb5\x02\n" +
	"\fAgentService\x12>\n" +
	"\aGetById\x12\x18.api.GetAgentByIdRequest\x1a\x19.api.GetAgentByIdResponse\x12=\n" +
	"\x06GetAll\x12\x18.api.GetAllAgentsRequest\x1a\x19.api.GetAllAgentsResponse\x125\n" +
	"\x04Post\x12\x15.api.PostAgentRequest\x1a\x16.api.PostAgentResponse\x122\n" +
	"\x03Put\x12\x14.api.PutAgentRequest\x1a\x15.api.PutAgentResponse\x12;\n" +
	"\x06Delete\x12\x17.api.DeleteAgentRequest\x1a\x18.api.DeleteAgentResponseB/Z-github.com/vv-sam/otus-project/proto/grpc/apib\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_proto_goTypes = []any{
	(*AgentInfo)(nil),            // 0: api.AgentInfo
	(*GetAgentByIdRequest)(nil),  // 1: api.GetAgentByIdRequest
	(*GetAgentByIdResponse)(nil), // 2: api.GetAgentByIdResponse
	(*GetAllAgentsRequest)(nil),  // 3: api.GetAllAgentsRequest
	(*GetAllAgentsResponse)(nil), // 4: api.GetAllAgentsResponse
	(*PostAgentRequest)(nil),     // 5: api.PostAgentRequest
	(*PostAgentResponse)(nil),    // 6: api.PostAgentResponse
	(*PutAgentRequest)(nil),      // 7: api.PutAgentRequest
	(*PutAgentResponse)(nil),     // 8: api.PutAgentResponse
	(*DeleteAgentRequest)(nil),   // 9: api.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),  // 10: api.DeleteAgentResponse
	(*Task)(nil),                 // 11: api.Task
	(*HostMetrics)(nil),          // 12: api.HostMetrics
}
var file_agent_proto_depIdxs = []int32{
	11, // 0: api.AgentInfo.current_tasks:type_name -> api.Task
	12, // 1: api.AgentInfo.metrics:type_name -> api.HostMetrics
	0,  // 2: api.GetAgentByIdResponse.agent:type_name -> api.AgentInfo
	0,  // 3: api.GetAllAgentsResponse.agents:type_name -> api.AgentInfo
	0,  // 4: api.PostAgentRequest.agent:type_name -> api.AgentInfo
	0,  // 5: api.PutAgentRequest.agent:type_name -> api.AgentInfo
	1,  // 6: api.AgentService.GetById:input_type -> api.GetAgentByIdRequest
	3,  // 7: api.AgentService.GetAll:input_type -> api.GetAllAgentsRequest
	5,  // 8: api.AgentService.Post:input_type -> api.PostAgentRequest
	7,  // 9: api.AgentService.Put:input_type -> api.PutAgentRequest
	9,  // 10: api.AgentService.Delete:input_type -> api.DeleteAgentRequest
	2,  // 11: api.AgentService.GetById:output_type -> api.GetAgentByIdResponse
	4,  // 12: api.AgentService.GetAll:output_type -> api.GetAllAgentsResponse
	6,  // 13: api.AgentService.Post:output_type -> api.PostAgentResponse
	8,  // 14: api.AgentService.Put:output_type -> api.PutAgentResponse
	10, // 15: api.AgentService.Delete:output_type -> api.DeleteAgentResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_task_proto_init()
	file_metrics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
