// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: configuration.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigurationType int32

const (
	ConfigurationType_CONFIGURATION_TYPE_UNSPECIFIED ConfigurationType = 0
	ConfigurationType_CONFIGURATION_TYPE_FACTORIO    ConfigurationType = 1
	ConfigurationType_CONFIGURATION_TYPE_MINECRAFT   ConfigurationType = 2
)

// Enum value maps for ConfigurationType.
var (
	ConfigurationType_name = map[int32]string{
		0: "CONFIGURATION_TYPE_UNSPECIFIED",
		1: "CONFIGURATION_TYPE_FACTORIO",
		2: "CONFIGURATION_TYPE_MINECRAFT",
	}
	ConfigurationType_value = map[string]int32{
		"CONFIGURATION_TYPE_UNSPECIFIED": 0,
		"CONFIGURATION_TYPE_FACTORIO":    1,
		"CONFIGURATION_TYPE_MINECRAFT":   2,
	}
)

func (x ConfigurationType) Enum() *ConfigurationType {
	p := new(ConfigurationType)
	*p = x
	return p
}

func (x ConfigurationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigurationType) Descriptor() protoreflect.EnumDescriptor {
	return file_configuration_proto_enumTypes[0].Descriptor()
}

func (ConfigurationType) Type() protoreflect.EnumType {
	return &file_configuration_proto_enumTypes[0]
}

func (x ConfigurationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigurationType.Descriptor instead.
func (ConfigurationType) EnumDescriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

type MinecraftGamemode int32

const (
	MinecraftGamemode_MINECRAFT_GAMEMODE_UNSPECIFIED MinecraftGamemode = 0
	MinecraftGamemode_MINECRAFT_GAMEMODE_SURVIVAL    MinecraftGamemode = 1
	MinecraftGamemode_MINECRAFT_GAMEMODE_CREATIVE    MinecraftGamemode = 2
	MinecraftGamemode_MINECRAFT_GAMEMODE_ADVENTURE   MinecraftGamemode = 3
	MinecraftGamemode_MINECRAFT_GAMEMODE_SPECTATOR   MinecraftGamemode = 4
)

// Enum value maps for MinecraftGamemode.
var (
	MinecraftGamemode_name = map[int32]string{
		0: "MINECRAFT_GAMEMODE_UNSPECIFIED",
		1: "MINECRAFT_GAMEMODE_SURVIVAL",
		2: "MINECRAFT_GAMEMODE_CREATIVE",
		3: "MINECRAFT_GAMEMODE_ADVENTURE",
		4: "MINECRAFT_GAMEMODE_SPECTATOR",
	}
	MinecraftGamemode_value = map[string]int32{
		"MINECRAFT_GAMEMODE_UNSPECIFIED": 0,
		"MINECRAFT_GAMEMODE_SURVIVAL":    1,
		"MINECRAFT_GAMEMODE_CREATIVE":    2,
		"MINECRAFT_GAMEMODE_ADVENTURE":   3,
		"MINECRAFT_GAMEMODE_SPECTATOR":   4,
	}
)

func (x MinecraftGamemode) Enum() *MinecraftGamemode {
	p := new(MinecraftGamemode)
	*p = x
	return p
}

func (x MinecraftGamemode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinecraftGamemode) Descriptor() protoreflect.EnumDescriptor {
	return file_configuration_proto_enumTypes[1].Descriptor()
}

func (MinecraftGamemode) Type() protoreflect.EnumType {
	return &file_configuration_proto_enumTypes[1]
}

func (x MinecraftGamemode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MinecraftGamemode.Descriptor instead.
func (MinecraftGamemode) EnumDescriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

type BaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Type          ConfigurationType      `protobuf:"varint,4,opt,name=type,proto3,enum=api.ConfigurationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseConfig) Reset() {
	*x = BaseConfig{}
	mi := &file_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseConfig) ProtoMessage() {}

func (x *BaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseConfig.ProtoReflect.Descriptor instead.
func (*BaseConfig) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *BaseConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseConfig) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BaseConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BaseConfig) GetType() ConfigurationType {
	if x != nil {
		return x.Type
	}
	return ConfigurationType_CONFIGURATION_TYPE_UNSPECIFIED
}

type FactorioServerSettings struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	Name                                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description                          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags                                 []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	MaxPlayers                           int32                  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Username                             string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Token                                string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	RequireUserVerification              bool                   `protobuf:"varint,7,opt,name=require_user_verification,json=requireUserVerification,proto3" json:"require_user_verification,omitempty"`
	MaxUploadInKilobytesPerSecond        int32                  `protobuf:"varint,8,opt,name=max_upload_in_kilobytes_per_second,json=maxUploadInKilobytesPerSecond,proto3" json:"max_upload_in_kilobytes_per_second,omitempty"`
	MaxUploadSlots                       int32                  `protobuf:"varint,9,opt,name=max_upload_slots,json=maxUploadSlots,proto3" json:"max_upload_slots,omitempty"`
	MinimumLatencyInTicks                int32                  `protobuf:"varint,10,opt,name=minimum_latency_in_ticks,json=minimumLatencyInTicks,proto3" json:"minimum_latency_in_ticks,omitempty"`
	MaxHeartbeatsPerSecond               int32                  `protobuf:"varint,11,opt,name=max_heartbeats_per_second,json=maxHeartbeatsPerSecond,proto3" json:"max_heartbeats_per_second,omitempty"`
	IgnorePlayerLimitForReturningPlayers bool                   `protobuf:"varint,12,opt,name=ignore_player_limit_for_returning_players,json=ignorePlayerLimitForReturningPlayers,proto3" json:"ignore_player_limit_for_returning_players,omitempty"`
	AllowCommands                        string                 `protobuf:"bytes,13,opt,name=allow_commands,json=allowCommands,proto3" json:"allow_commands,omitempty"`
	AutosaveInterval                     int32                  `protobuf:"varint,14,opt,name=autosave_interval,json=autosaveInterval,proto3" json:"autosave_interval,omitempty"`
	AutosaveSlots                        int32                  `protobuf:"varint,15,opt,name=autosave_slots,json=autosaveSlots,proto3" json:"autosave_slots,omitempty"`
	AfkAutokickInterval                  int32                  `protobuf:"varint,16,opt,name=afk_autokick_interval,json=afkAutokickInterval,proto3" json:"afk_autokick_interval,omitempty"`
	AutoPause                            bool                   `protobuf:"varint,17,opt,name=auto_pause,json=autoPause,proto3" json:"auto_pause,omitempty"`
	AutoPauseWhenPlayersConnect          bool                   `protobuf:"varint,18,opt,name=auto_pause_when_players_connect,json=autoPauseWhenPlayersConnect,proto3" json:"auto_pause_when_players_connect,omitempty"`
	OnlyAdminsCanPauseTheGame            bool                   `protobuf:"varint,19,opt,name=only_admins_can_pause_the_game,json=onlyAdminsCanPauseTheGame,proto3" json:"only_admins_can_pause_the_game,omitempty"`
	AutosaveOnlyOnServer                 bool                   `protobuf:"varint,20,opt,name=autosave_only_on_server,json=autosaveOnlyOnServer,proto3" json:"autosave_only_on_server,omitempty"`
	NonBlockingSaving                    bool                   `protobuf:"varint,21,opt,name=non_blocking_saving,json=nonBlockingSaving,proto3" json:"non_blocking_saving,omitempty"`
	MinimumSegmentSize                   int32                  `protobuf:"varint,22,opt,name=minimum_segment_size,json=minimumSegmentSize,proto3" json:"minimum_segment_size,omitempty"`
	MinimumSegmentSizePeerCount          int32                  `protobuf:"varint,23,opt,name=minimum_segment_size_peer_count,json=minimumSegmentSizePeerCount,proto3" json:"minimum_segment_size_peer_count,omitempty"`
	MaximumSegmentSize                   int32                  `protobuf:"varint,24,opt,name=maximum_segment_size,json=maximumSegmentSize,proto3" json:"maximum_segment_size,omitempty"`
	MaximumSegmentSizePeerCount          int32                  `protobuf:"varint,25,opt,name=maximum_segment_size_peer_count,json=maximumSegmentSizePeerCount,proto3" json:"maximum_segment_size_peer_count,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *FactorioServerSettings) Reset() {
	*x = FactorioServerSettings{}
	mi := &file_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioServerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioServerSettings) ProtoMessage() {}

func (x *FactorioServerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioServerSettings.ProtoReflect.Descriptor instead.
func (*FactorioServerSettings) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *FactorioServerSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactorioServerSettings) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FactorioServerSettings) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FactorioServerSettings) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *FactorioServerSettings) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FactorioServerSettings) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FactorioServerSettings) GetRequireUserVerification() bool {
	if x != nil {
		return x.RequireUserVerification
	}
	return false
}

func (x *FactorioServerSettings) GetMaxUploadInKilobytesPerSecond() int32 {
	if x != nil {
		return x.MaxUploadInKilobytesPerSecond
	}
	return 0
}

func (x *FactorioServerSettings) GetMaxUploadSlots() int32 {
	if x != nil {
		return x.MaxUploadSlots
	}
	return 0
}

func (x *FactorioServerSettings) GetMinimumLatencyInTicks() int32 {
	if x != nil {
		return x.MinimumLatencyInTicks
	}
	return 0
}

func (x *FactorioServerSettings) GetMaxHeartbeatsPerSecond() int32 {
	if x != nil {
		return x.MaxHeartbeatsPerSecond
	}
	return 0
}

func (x *FactorioServerSettings) GetIgnorePlayerLimitForReturningPlayers() bool {
	if x != nil {
		return x.IgnorePlayerLimitForReturningPlayers
	}
	return false
}

func (x *FactorioServerSettings) GetAllowCommands() string {
	if x != nil {
		return x.AllowCommands
	}
	return ""
}

func (x *FactorioServerSettings) GetAutosaveInterval() int32 {
	if x != nil {
		return x.AutosaveInterval
	}
	return 0
}

func (x *FactorioServerSettings) GetAutosaveSlots() int32 {
	if x != nil {
		return x.AutosaveSlots
	}
	return 0
}

func (x *FactorioServerSettings) GetAfkAutokickInterval() int32 {
	if x != nil {
		return x.AfkAutokickInterval
	}
	return 0
}

func (x *FactorioServerSettings) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *FactorioServerSettings) GetAutoPauseWhenPlayersConnect() bool {
	if x != nil {
		return x.AutoPauseWhenPlayersConnect
	}
	return false
}

func (x *FactorioServerSettings) GetOnlyAdminsCanPauseTheGame() bool {
	if x != nil {
		return x.OnlyAdminsCanPauseTheGame
	}
	return false
}

func (x *FactorioServerSettings) GetAutosaveOnlyOnServer() bool {
	if x != nil {
		return x.AutosaveOnlyOnServer
	}
	return false
}

func (x *FactorioServerSettings) GetNonBlockingSaving() bool {
	if x != nil {
		return x.NonBlockingSaving
	}
	return false
}

func (x *FactorioServerSettings) GetMinimumSegmentSize() int32 {
	if x != nil {
		return x.MinimumSegmentSize
	}
	return 0
}

func (x *FactorioServerSettings) GetMinimumSegmentSizePeerCount() int32 {
	if x != nil {
		return x.MinimumSegmentSizePeerCount
	}
	return 0
}

func (x *FactorioServerSettings) GetMaximumSegmentSize() int32 {
	if x != nil {
		return x.MaximumSegmentSize
	}
	return 0
}

func (x *FactorioServerSettings) GetMaximumSegmentSizePeerCount() int32 {
	if x != nil {
		return x.MaximumSegmentSizePeerCount
	}
	return 0
}

type FactorioDifficultySettings struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TechnologyPriceMultiplier float32                `protobuf:"fixed32,1,opt,name=technology_price_multiplier,json=technologyPriceMultiplier,proto3" json:"technology_price_multiplier,omitempty"`
	SpoilTimeModifier         float32                `protobuf:"fixed32,2,opt,name=spoil_time_modifier,json=spoilTimeModifier,proto3" json:"spoil_time_modifier,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *FactorioDifficultySettings) Reset() {
	*x = FactorioDifficultySettings{}
	mi := &file_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioDifficultySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioDifficultySettings) ProtoMessage() {}

func (x *FactorioDifficultySettings) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioDifficultySettings.ProtoReflect.Descriptor instead.
func (*FactorioDifficultySettings) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *FactorioDifficultySettings) GetTechnologyPriceMultiplier() float32 {
	if x != nil {
		return x.TechnologyPriceMultiplier
	}
	return 0
}

func (x *FactorioDifficultySettings) GetSpoilTimeModifier() float32 {
	if x != nil {
		return x.SpoilTimeModifier
	}
	return 0
}

type FactorioPollutionSettings struct {
	state                                   protoimpl.MessageState `protogen:"open.v1"`
	Enabled                                 bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DiffusionRatio                          float64                `protobuf:"fixed64,2,opt,name=diffusion_ratio,json=diffusionRatio,proto3" json:"diffusion_ratio,omitempty"`
	MinToDiffuse                            int32                  `protobuf:"varint,3,opt,name=min_to_diffuse,json=minToDiffuse,proto3" json:"min_to_diffuse,omitempty"`
	Ageing                                  int32                  `protobuf:"varint,4,opt,name=ageing,proto3" json:"ageing,omitempty"`
	ExpectedMaxPerChunk                     int32                  `protobuf:"varint,5,opt,name=expected_max_per_chunk,json=expectedMaxPerChunk,proto3" json:"expected_max_per_chunk,omitempty"`
	MinToShowPerChunk                       int32                  `protobuf:"varint,6,opt,name=min_to_show_per_chunk,json=minToShowPerChunk,proto3" json:"min_to_show_per_chunk,omitempty"`
	MinPollutionToDamageTrees               int32                  `protobuf:"varint,7,opt,name=min_pollution_to_damage_trees,json=minPollutionToDamageTrees,proto3" json:"min_pollution_to_damage_trees,omitempty"`
	PollutionWithMaxForestDamage            int32                  `protobuf:"varint,8,opt,name=pollution_with_max_forest_damage,json=pollutionWithMaxForestDamage,proto3" json:"pollution_with_max_forest_damage,omitempty"`
	PollutionPerTreeDamage                  int32                  `protobuf:"varint,9,opt,name=pollution_per_tree_damage,json=pollutionPerTreeDamage,proto3" json:"pollution_per_tree_damage,omitempty"`
	PollutionRestoredPerTreeDamage          int32                  `protobuf:"varint,10,opt,name=pollution_restored_per_tree_damage,json=pollutionRestoredPerTreeDamage,proto3" json:"pollution_restored_per_tree_damage,omitempty"`
	MaxPollutionToRestoreTrees              int32                  `protobuf:"varint,11,opt,name=max_pollution_to_restore_trees,json=maxPollutionToRestoreTrees,proto3" json:"max_pollution_to_restore_trees,omitempty"`
	EnemyAttackPollutionConsumptionModifier int32                  `protobuf:"varint,12,opt,name=enemy_attack_pollution_consumption_modifier,json=enemyAttackPollutionConsumptionModifier,proto3" json:"enemy_attack_pollution_consumption_modifier,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *FactorioPollutionSettings) Reset() {
	*x = FactorioPollutionSettings{}
	mi := &file_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioPollutionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioPollutionSettings) ProtoMessage() {}

func (x *FactorioPollutionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioPollutionSettings.ProtoReflect.Descriptor instead.
func (*FactorioPollutionSettings) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *FactorioPollutionSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FactorioPollutionSettings) GetDiffusionRatio() float64 {
	if x != nil {
		return x.DiffusionRatio
	}
	return 0
}

func (x *FactorioPollutionSettings) GetMinToDiffuse() int32 {
	if x != nil {
		return x.MinToDiffuse
	}
	return 0
}

func (x *FactorioPollutionSettings) GetAgeing() int32 {
	if x != nil {
		return x.Ageing
	}
	return 0
}

func (x *FactorioPollutionSettings) GetExpectedMaxPerChunk() int32 {
	if x != nil {
		return x.ExpectedMaxPerChunk
	}
	return 0
}

func (x *FactorioPollutionSettings) GetMinToShowPerChunk() int32 {
	if x != nil {
		return x.MinToShowPerChunk
	}
	return 0
}

func (x *FactorioPollutionSettings) GetMinPollutionToDamageTrees() int32 {
	if x != nil {
		return x.MinPollutionToDamageTrees
	}
	return 0
}

func (x *FactorioPollutionSettings) GetPollutionWithMaxForestDamage() int32 {
	if x != nil {
		return x.PollutionWithMaxForestDamage
	}
	return 0
}

func (x *FactorioPollutionSettings) GetPollutionPerTreeDamage() int32 {
	if x != nil {
		return x.PollutionPerTreeDamage
	}
	return 0
}

func (x *FactorioPollutionSettings) GetPollutionRestoredPerTreeDamage() int32 {
	if x != nil {
		return x.PollutionRestoredPerTreeDamage
	}
	return 0
}

func (x *FactorioPollutionSettings) GetMaxPollutionToRestoreTrees() int32 {
	if x != nil {
		return x.MaxPollutionToRestoreTrees
	}
	return 0
}

func (x *FactorioPollutionSettings) GetEnemyAttackPollutionConsumptionModifier() int32 {
	if x != nil {
		return x.EnemyAttackPollutionConsumptionModifier
	}
	return 0
}

type FactorioEnemyEvolution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TimeFactor      float64                `protobuf:"fixed64,2,opt,name=time_factor,json=timeFactor,proto3" json:"time_factor,omitempty"`
	DestroyFactor   float64                `protobuf:"fixed64,3,opt,name=destroy_factor,json=destroyFactor,proto3" json:"destroy_factor,omitempty"`
	PollutionFactor float64                `protobuf:"fixed64,4,opt,name=pollution_factor,json=pollutionFactor,proto3" json:"pollution_factor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FactorioEnemyEvolution) Reset() {
	*x = FactorioEnemyEvolution{}
	mi := &file_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioEnemyEvolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioEnemyEvolution) ProtoMessage() {}

func (x *FactorioEnemyEvolution) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioEnemyEvolution.ProtoReflect.Descriptor instead.
func (*FactorioEnemyEvolution) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *FactorioEnemyEvolution) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FactorioEnemyEvolution) GetTimeFactor() float64 {
	if x != nil {
		return x.TimeFactor
	}
	return 0
}

func (x *FactorioEnemyEvolution) GetDestroyFactor() float64 {
	if x != nil {
		return x.DestroyFactor
	}
	return 0
}

func (x *FactorioEnemyEvolution) GetPollutionFactor() float64 {
	if x != nil {
		return x.PollutionFactor
	}
	return 0
}

type FactorioEnemyExpansion struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Enabled                          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxExpansionDistance             int32                  `protobuf:"varint,2,opt,name=max_expansion_distance,json=maxExpansionDistance,proto3" json:"max_expansion_distance,omitempty"`
	FriendlyBaseInfluenceRadius      int32                  `protobuf:"varint,3,opt,name=friendly_base_influence_radius,json=friendlyBaseInfluenceRadius,proto3" json:"friendly_base_influence_radius,omitempty"`
	EnemyBuildingInfluenceRadius     int32                  `protobuf:"varint,4,opt,name=enemy_building_influence_radius,json=enemyBuildingInfluenceRadius,proto3" json:"enemy_building_influence_radius,omitempty"`
	BuildingCoefficient              float64                `protobuf:"fixed64,5,opt,name=building_coefficient,json=buildingCoefficient,proto3" json:"building_coefficient,omitempty"`
	OtherBaseCoefficient             float64                `protobuf:"fixed64,6,opt,name=other_base_coefficient,json=otherBaseCoefficient,proto3" json:"other_base_coefficient,omitempty"`
	NeighbouringChunkCoefficient     float64                `protobuf:"fixed64,7,opt,name=neighbouring_chunk_coefficient,json=neighbouringChunkCoefficient,proto3" json:"neighbouring_chunk_coefficient,omitempty"`
	NeighbouringBaseChunkCoefficient float64                `protobuf:"fixed64,8,opt,name=neighbouring_base_chunk_coefficient,json=neighbouringBaseChunkCoefficient,proto3" json:"neighbouring_base_chunk_coefficient,omitempty"`
	MaxCollidingTilesCoefficient     float64                `protobuf:"fixed64,9,opt,name=max_colliding_tiles_coefficient,json=maxCollidingTilesCoefficient,proto3" json:"max_colliding_tiles_coefficient,omitempty"`
	SettlerGroupMinSize              int32                  `protobuf:"varint,10,opt,name=settler_group_min_size,json=settlerGroupMinSize,proto3" json:"settler_group_min_size,omitempty"`
	SettlerGroupMaxSize              int32                  `protobuf:"varint,11,opt,name=settler_group_max_size,json=settlerGroupMaxSize,proto3" json:"settler_group_max_size,omitempty"`
	MinExpansionCooldown             int32                  `protobuf:"varint,12,opt,name=min_expansion_cooldown,json=minExpansionCooldown,proto3" json:"min_expansion_cooldown,omitempty"`
	MaxExpansionCooldown             int32                  `protobuf:"varint,13,opt,name=max_expansion_cooldown,json=maxExpansionCooldown,proto3" json:"max_expansion_cooldown,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *FactorioEnemyExpansion) Reset() {
	*x = FactorioEnemyExpansion{}
	mi := &file_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioEnemyExpansion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioEnemyExpansion) ProtoMessage() {}

func (x *FactorioEnemyExpansion) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioEnemyExpansion.ProtoReflect.Descriptor instead.
func (*FactorioEnemyExpansion) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *FactorioEnemyExpansion) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FactorioEnemyExpansion) GetMaxExpansionDistance() int32 {
	if x != nil {
		return x.MaxExpansionDistance
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetFriendlyBaseInfluenceRadius() int32 {
	if x != nil {
		return x.FriendlyBaseInfluenceRadius
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetEnemyBuildingInfluenceRadius() int32 {
	if x != nil {
		return x.EnemyBuildingInfluenceRadius
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetBuildingCoefficient() float64 {
	if x != nil {
		return x.BuildingCoefficient
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetOtherBaseCoefficient() float64 {
	if x != nil {
		return x.OtherBaseCoefficient
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetNeighbouringChunkCoefficient() float64 {
	if x != nil {
		return x.NeighbouringChunkCoefficient
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetNeighbouringBaseChunkCoefficient() float64 {
	if x != nil {
		return x.NeighbouringBaseChunkCoefficient
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetMaxCollidingTilesCoefficient() float64 {
	if x != nil {
		return x.MaxCollidingTilesCoefficient
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetSettlerGroupMinSize() int32 {
	if x != nil {
		return x.SettlerGroupMinSize
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetSettlerGroupMaxSize() int32 {
	if x != nil {
		return x.SettlerGroupMaxSize
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetMinExpansionCooldown() int32 {
	if x != nil {
		return x.MinExpansionCooldown
	}
	return 0
}

func (x *FactorioEnemyExpansion) GetMaxExpansionCooldown() int32 {
	if x != nil {
		return x.MaxExpansionCooldown
	}
	return 0
}

type FactorioUnitGroup struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	MinGroupGatheringTime          int32                  `protobuf:"varint,1,opt,name=min_group_gathering_time,json=minGroupGatheringTime,proto3" json:"min_group_gathering_time,omitempty"`
	MaxGroupGatheringTime          int32                  `protobuf:"varint,2,opt,name=max_group_gathering_time,json=maxGroupGatheringTime,proto3" json:"max_group_gathering_time,omitempty"`
	MaxWaitTimeForLateMembers      int32                  `protobuf:"varint,3,opt,name=max_wait_time_for_late_members,json=maxWaitTimeForLateMembers,proto3" json:"max_wait_time_for_late_members,omitempty"`
	MaxGroupRadius                 float64                `protobuf:"fixed64,4,opt,name=max_group_radius,json=maxGroupRadius,proto3" json:"max_group_radius,omitempty"`
	MinGroupRadius                 float64                `protobuf:"fixed64,5,opt,name=min_group_radius,json=minGroupRadius,proto3" json:"min_group_radius,omitempty"`
	MaxMemberSpeedupWhenBehind     float64                `protobuf:"fixed64,6,opt,name=max_member_speedup_when_behind,json=maxMemberSpeedupWhenBehind,proto3" json:"max_member_speedup_when_behind,omitempty"`
	MaxMemberSlowdownWhenAhead     float64                `protobuf:"fixed64,7,opt,name=max_member_slowdown_when_ahead,json=maxMemberSlowdownWhenAhead,proto3" json:"max_member_slowdown_when_ahead,omitempty"`
	MaxGroupSlowdownFactor         float64                `protobuf:"fixed64,8,opt,name=max_group_slowdown_factor,json=maxGroupSlowdownFactor,proto3" json:"max_group_slowdown_factor,omitempty"`
	MaxGroupMemberFallbackFactor   int32                  `protobuf:"varint,9,opt,name=max_group_member_fallback_factor,json=maxGroupMemberFallbackFactor,proto3" json:"max_group_member_fallback_factor,omitempty"`
	MemberDisownDistance           int32                  `protobuf:"varint,10,opt,name=member_disown_distance,json=memberDisownDistance,proto3" json:"member_disown_distance,omitempty"`
	TickToleranceWhenMemberArrives int32                  `protobuf:"varint,11,opt,name=tick_tolerance_when_member_arrives,json=tickToleranceWhenMemberArrives,proto3" json:"tick_tolerance_when_member_arrives,omitempty"`
	MaxGatheringUnitGroups         int32                  `protobuf:"varint,12,opt,name=max_gathering_unit_groups,json=maxGatheringUnitGroups,proto3" json:"max_gathering_unit_groups,omitempty"`
	MaxUnitGroupSize               int32                  `protobuf:"varint,13,opt,name=max_unit_group_size,json=maxUnitGroupSize,proto3" json:"max_unit_group_size,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *FactorioUnitGroup) Reset() {
	*x = FactorioUnitGroup{}
	mi := &file_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioUnitGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioUnitGroup) ProtoMessage() {}

func (x *FactorioUnitGroup) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioUnitGroup.ProtoReflect.Descriptor instead.
func (*FactorioUnitGroup) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{6}
}

func (x *FactorioUnitGroup) GetMinGroupGatheringTime() int32 {
	if x != nil {
		return x.MinGroupGatheringTime
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxGroupGatheringTime() int32 {
	if x != nil {
		return x.MaxGroupGatheringTime
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxWaitTimeForLateMembers() int32 {
	if x != nil {
		return x.MaxWaitTimeForLateMembers
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxGroupRadius() float64 {
	if x != nil {
		return x.MaxGroupRadius
	}
	return 0
}

func (x *FactorioUnitGroup) GetMinGroupRadius() float64 {
	if x != nil {
		return x.MinGroupRadius
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxMemberSpeedupWhenBehind() float64 {
	if x != nil {
		return x.MaxMemberSpeedupWhenBehind
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxMemberSlowdownWhenAhead() float64 {
	if x != nil {
		return x.MaxMemberSlowdownWhenAhead
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxGroupSlowdownFactor() float64 {
	if x != nil {
		return x.MaxGroupSlowdownFactor
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxGroupMemberFallbackFactor() int32 {
	if x != nil {
		return x.MaxGroupMemberFallbackFactor
	}
	return 0
}

func (x *FactorioUnitGroup) GetMemberDisownDistance() int32 {
	if x != nil {
		return x.MemberDisownDistance
	}
	return 0
}

func (x *FactorioUnitGroup) GetTickToleranceWhenMemberArrives() int32 {
	if x != nil {
		return x.TickToleranceWhenMemberArrives
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxGatheringUnitGroups() int32 {
	if x != nil {
		return x.MaxGatheringUnitGroups
	}
	return 0
}

func (x *FactorioUnitGroup) GetMaxUnitGroupSize() int32 {
	if x != nil {
		return x.MaxUnitGroupSize
	}
	return 0
}

type FactorioMapSettings struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	DifficultySettings *FactorioDifficultySettings `protobuf:"bytes,1,opt,name=difficulty_settings,json=difficultySettings,proto3" json:"difficulty_settings,omitempty"`
	Pollution          *FactorioPollutionSettings  `protobuf:"bytes,2,opt,name=pollution,proto3" json:"pollution,omitempty"`
	EnemyEvolution     *FactorioEnemyEvolution     `protobuf:"bytes,3,opt,name=enemy_evolution,json=enemyEvolution,proto3" json:"enemy_evolution,omitempty"`
	EnemyExpansion     *FactorioEnemyExpansion     `protobuf:"bytes,4,opt,name=enemy_expansion,json=enemyExpansion,proto3" json:"enemy_expansion,omitempty"`
	UnitGroup          *FactorioUnitGroup          `protobuf:"bytes,5,opt,name=unit_group,json=unitGroup,proto3" json:"unit_group,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FactorioMapSettings) Reset() {
	*x = FactorioMapSettings{}
	mi := &file_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioMapSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioMapSettings) ProtoMessage() {}

func (x *FactorioMapSettings) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioMapSettings.ProtoReflect.Descriptor instead.
func (*FactorioMapSettings) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{7}
}

func (x *FactorioMapSettings) GetDifficultySettings() *FactorioDifficultySettings {
	if x != nil {
		return x.DifficultySettings
	}
	return nil
}

func (x *FactorioMapSettings) GetPollution() *FactorioPollutionSettings {
	if x != nil {
		return x.Pollution
	}
	return nil
}

func (x *FactorioMapSettings) GetEnemyEvolution() *FactorioEnemyEvolution {
	if x != nil {
		return x.EnemyEvolution
	}
	return nil
}

func (x *FactorioMapSettings) GetEnemyExpansion() *FactorioEnemyExpansion {
	if x != nil {
		return x.EnemyExpansion
	}
	return nil
}

func (x *FactorioMapSettings) GetUnitGroup() *FactorioUnitGroup {
	if x != nil {
		return x.UnitGroup
	}
	return nil
}

type FactorioResourceSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     float32                `protobuf:"fixed32,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Size          float32                `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
	Richness      float32                `protobuf:"fixed32,3,opt,name=richness,proto3" json:"richness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorioResourceSettings) Reset() {
	*x = FactorioResourceSettings{}
	mi := &file_configuration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioResourceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioResourceSettings) ProtoMessage() {}

func (x *FactorioResourceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioResourceSettings.ProtoReflect.Descriptor instead.
func (*FactorioResourceSettings) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{8}
}

func (x *FactorioResourceSettings) GetFrequency() float32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *FactorioResourceSettings) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FactorioResourceSettings) GetRichness() float32 {
	if x != nil {
		return x.Richness
	}
	return 0
}

type FactorioCliffSettings struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CliffElevation_0       int32                  `protobuf:"varint,2,opt,name=cliff_elevation_0,json=cliffElevation0,proto3" json:"cliff_elevation_0,omitempty"`
	CliffElevationInterval int32                  `protobuf:"varint,3,opt,name=cliff_elevation_interval,json=cliffElevationInterval,proto3" json:"cliff_elevation_interval,omitempty"`
	Richness               int32                  `protobuf:"varint,4,opt,name=richness,proto3" json:"richness,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FactorioCliffSettings) Reset() {
	*x = FactorioCliffSettings{}
	mi := &file_configuration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioCliffSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioCliffSettings) ProtoMessage() {}

func (x *FactorioCliffSettings) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioCliffSettings.ProtoReflect.Descriptor instead.
func (*FactorioCliffSettings) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{9}
}

func (x *FactorioCliffSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactorioCliffSettings) GetCliffElevation_0() int32 {
	if x != nil {
		return x.CliffElevation_0
	}
	return 0
}

func (x *FactorioCliffSettings) GetCliffElevationInterval() int32 {
	if x != nil {
		return x.CliffElevationInterval
	}
	return 0
}

func (x *FactorioCliffSettings) GetRichness() int32 {
	if x != nil {
		return x.Richness
	}
	return 0
}

type FactorioMapGenSettings struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	Width             int32                                `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height            int32                                `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	StartingArea      int32                                `protobuf:"varint,3,opt,name=starting_area,json=startingArea,proto3" json:"starting_area,omitempty"`
	PeacefulMode      bool                                 `protobuf:"varint,4,opt,name=peaceful_mode,json=peacefulMode,proto3" json:"peaceful_mode,omitempty"`
	AutoplaceControls map[string]*FactorioResourceSettings `protobuf:"bytes,5,rep,name=autoplace_controls,json=autoplaceControls,proto3" json:"autoplace_controls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CliffSettings     *FactorioCliffSettings               `protobuf:"bytes,6,opt,name=cliff_settings,json=cliffSettings,proto3" json:"cliff_settings,omitempty"`
	Seed              int32                                `protobuf:"varint,7,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FactorioMapGenSettings) Reset() {
	*x = FactorioMapGenSettings{}
	mi := &file_configuration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioMapGenSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioMapGenSettings) ProtoMessage() {}

func (x *FactorioMapGenSettings) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioMapGenSettings.ProtoReflect.Descriptor instead.
func (*FactorioMapGenSettings) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{10}
}

func (x *FactorioMapGenSettings) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FactorioMapGenSettings) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FactorioMapGenSettings) GetStartingArea() int32 {
	if x != nil {
		return x.StartingArea
	}
	return 0
}

func (x *FactorioMapGenSettings) GetPeacefulMode() bool {
	if x != nil {
		return x.PeacefulMode
	}
	return false
}

func (x *FactorioMapGenSettings) GetAutoplaceControls() map[string]*FactorioResourceSettings {
	if x != nil {
		return x.AutoplaceControls
	}
	return nil
}

func (x *FactorioMapGenSettings) GetCliffSettings() *FactorioCliffSettings {
	if x != nil {
		return x.CliffSettings
	}
	return nil
}

func (x *FactorioMapGenSettings) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type FactorioConfig struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Base          *BaseConfig             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Server        *FactorioServerSettings `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Map           *FactorioMapSettings    `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	MapGen        *FactorioMapGenSettings `protobuf:"bytes,4,opt,name=map_gen,json=mapGen,proto3" json:"map_gen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorioConfig) Reset() {
	*x = FactorioConfig{}
	mi := &file_configuration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorioConfig) ProtoMessage() {}

func (x *FactorioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorioConfig.ProtoReflect.Descriptor instead.
func (*FactorioConfig) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{11}
}

func (x *FactorioConfig) GetBase() *BaseConfig {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FactorioConfig) GetServer() *FactorioServerSettings {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *FactorioConfig) GetMap() *FactorioMapSettings {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *FactorioConfig) GetMapGen() *FactorioMapGenSettings {
	if x != nil {
		return x.MapGen
	}
	return nil
}

type MinecraftConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseConfig            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Seed          string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	RconPort      uint32                 `protobuf:"varint,3,opt,name=rcon_port,json=rconPort,proto3" json:"rcon_port,omitempty"`
	Gamemode      MinecraftGamemode      `protobuf:"varint,4,opt,name=gamemode,proto3,enum=api.MinecraftGamemode" json:"gamemode,omitempty"`
	ServerName    string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	MaxPlayers    uint32                 `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	ViewDistance  int32                  `protobuf:"varint,7,opt,name=view_distance,json=viewDistance,proto3" json:"view_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinecraftConfig) Reset() {
	*x = MinecraftConfig{}
	mi := &file_configuration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinecraftConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinecraftConfig) ProtoMessage() {}

func (x *MinecraftConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinecraftConfig.ProtoReflect.Descriptor instead.
func (*MinecraftConfig) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{12}
}

func (x *MinecraftConfig) GetBase() *BaseConfig {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MinecraftConfig) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *MinecraftConfig) GetRconPort() uint32 {
	if x != nil {
		return x.RconPort
	}
	return 0
}

func (x *MinecraftConfig) GetGamemode() MinecraftGamemode {
	if x != nil {
		return x.Gamemode
	}
	return MinecraftGamemode_MINECRAFT_GAMEMODE_UNSPECIFIED
}

func (x *MinecraftConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *MinecraftConfig) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *MinecraftConfig) GetViewDistance() int32 {
	if x != nil {
		return x.ViewDistance
	}
	return 0
}

type GetConfigByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigByIdRequest) Reset() {
	*x = GetConfigByIdRequest{}
	mi := &file_configuration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigByIdRequest) ProtoMessage() {}

func (x *GetConfigByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigByIdRequest.ProtoReflect.Descriptor instead.
func (*GetConfigByIdRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetConfigByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *FactorioConfig        `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigByIdResponse) Reset() {
	*x = GetConfigByIdResponse{}
	mi := &file_configuration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigByIdResponse) ProtoMessage() {}

func (x *GetConfigByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigByIdResponse.ProtoReflect.Descriptor instead.
func (*GetConfigByIdResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{14}
}

func (x *GetConfigByIdResponse) GetConfiguration() *FactorioConfig {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type GetAllConfigurationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllConfigurationsRequest) Reset() {
	*x = GetAllConfigurationsRequest{}
	mi := &file_configuration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllConfigurationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllConfigurationsRequest) ProtoMessage() {}

func (x *GetAllConfigurationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllConfigurationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllConfigurationsRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{15}
}

type GetAllConfigurationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Configurations []*FactorioConfig      `protobuf:"bytes,1,rep,name=configurations,proto3" json:"configurations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllConfigurationsResponse) Reset() {
	*x = GetAllConfigurationsResponse{}
	mi := &file_configuration_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllConfigurationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllConfigurationsResponse) ProtoMessage() {}

func (x *GetAllConfigurationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllConfigurationsResponse.ProtoReflect.Descriptor instead.
func (*GetAllConfigurationsResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllConfigurationsResponse) GetConfigurations() []*FactorioConfig {
	if x != nil {
		return x.Configurations
	}
	return nil
}

type PostConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *FactorioConfig        `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostConfigurationRequest) Reset() {
	*x = PostConfigurationRequest{}
	mi := &file_configuration_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostConfigurationRequest) ProtoMessage() {}

func (x *PostConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostConfigurationRequest.ProtoReflect.Descriptor instead.
func (*PostConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{17}
}

func (x *PostConfigurationRequest) GetConfiguration() *FactorioConfig {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type PostConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostConfigurationResponse) Reset() {
	*x = PostConfigurationResponse{}
	mi := &file_configuration_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostConfigurationResponse) ProtoMessage() {}

func (x *PostConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostConfigurationResponse.ProtoReflect.Descriptor instead.
func (*PostConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{18}
}

type PutConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Configuration *FactorioConfig        `protobuf:"bytes,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutConfigurationRequest) Reset() {
	*x = PutConfigurationRequest{}
	mi := &file_configuration_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutConfigurationRequest) ProtoMessage() {}

func (x *PutConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutConfigurationRequest.ProtoReflect.Descriptor instead.
func (*PutConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{19}
}

func (x *PutConfigurationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutConfigurationRequest) GetConfiguration() *FactorioConfig {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type PutConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutConfigurationResponse) Reset() {
	*x = PutConfigurationResponse{}
	mi := &file_configuration_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutConfigurationResponse) ProtoMessage() {}

func (x *PutConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutConfigurationResponse.ProtoReflect.Descriptor instead.
func (*PutConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{20}
}

type DeleteConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigurationRequest) Reset() {
	*x = DeleteConfigurationRequest{}
	mi := &file_configuration_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigurationRequest) ProtoMessage() {}

func (x *DeleteConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigurationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteConfigurationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigurationResponse) Reset() {
	*x = DeleteConfigurationResponse{}
	mi := &file_configuration_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigurationResponse) ProtoMessage() {}

func (x *DeleteConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigurationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{22}
}

var File_configuration_proto protoreflect.FileDescriptor

const file_configuration_proto_rawDesc = "" +
	"\n" +
	"\x13configuration.proto\x12\x03api\"w\n" +
	"\n" +
	"BaseConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.api.ConfigurationTypeR\x04type\"\xe1\t\n" +
	"\x16FactorioServerSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1f\n" +
	"\vmax_players\x18\x04 \x01(\x05R\n" +
	"maxPlayers\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x12:\n" +
	"\x19require_user_verification\x18\a \x01(\bR\x17requireUserVerification\x12I\n" +
	"\"max_upload_in_kilobytes_per_second\x18\b \x01(\x05R\x1dmaxUploadInKilobytesPerSecond\x12(\n" +
	"\x10max_upload_slots\x18\t \x01(\x05R\x0emaxUploadSlots\x127\n" +
	"\x18minimum_latency_in_ticks\x18\n" +
	" \x01(\x05R\x15minimumLatencyInTicks\x129\n" +
	"\x19max_heartbeats_per_second\x18\v \x01(\x05R\x16maxHeartbeatsPerSecond\x12W\n" +
	")ignore_player_limit_for_returning_players\x18\f \x01(\bR$ignorePlayerLimitForReturningPlayers\x12%\n" +
	"\x0eallow_commands\x18\r \x01(\tR\rallowCommands\x12+\n" +
	"\x11autosave_interval\x18\x0e \x01(\x05R\x10autosaveInterval\x12%\n" +
	"\x0eautosave_slots\x18\x0f \x01(\x05R\rautosaveSlots\x122\n" +
	"\x15afk_autokick_interval\x18\x10 \x01(\x05R\x13afkAutokickInterval\x12\x1d\n" +
	"\n" +
	"auto_pause\x18\x11 \x01(\bR\tautoPause\x12D\n" +
	"\x1fauto_pause_when_players_connect\x18\x12 \x01(\bR\x1bautoPauseWhenPlayersConnect\x12A\n" +
	"\x1eonly_admins_can_pause_the_game\x18\x13 \x01(\bR\x19onlyAdminsCanPauseTheGame\x125\n" +
	"\x17autosave_only_on_server\x18\x14 \x01(\bR\x14autosaveOnlyOnServer\x12.\n" +
	"\x13non_blocking_saving\x18\x15 \x01(\bR\x11nonBlockingSaving\x120\n" +
	"\x14minimum_segment_size\x18\x16 \x01(\x05R\x12minimumSegmentSize\x12D\n" +
	"\x1fminimum_segment_size_peer_count\x18\x17 \x01(\x05R\x1bminimumSegmentSizePeerCount\x120\n" +
	"\x14maximum_segment_size\x18\x18 \x01(\x05R\x12maximumSegmentSize\x12D\n" +
	"\x1fmaximum_segment_size_peer_count\x18\x19 \x01(\x05R\x1bmaximumSegmentSizePeerCount\"\x8c\x01\n" +
	"\x1aFactorioDifficultySettings\x12>\n" +
	"\x1btechnology_price_multiplier\x18\x01 \x01(\x02R\x19technologyPriceMultiplier\x12.\n" +
	"\x13spoil_time_modifier\x18\x02 \x01(\x02R\x11spoilTimeModifier\"\xb6\x05\n" +
	"\x19FactorioPollutionSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x0fdiffusion_ratio\x18\x02 \x01(\x01R\x0ediffusionRatio\x12$\n" +
	"\x0emin_to_diffuse\x18\x03 \x01(\x05R\fminToDiffuse\x12\x16\n" +
	"\x06ageing\x18\x04 \x01(\x05R\x06ageing\x123\n" +
	"\x16expected_max_per_chunk\x18\x05 \x01(\x05R\x13expectedMaxPerChunk\x120\n" +
	"\x15min_to_show_per_chunk\x18\x06 \x01(\x05R\x11minToShowPerChunk\x12@\n" +
	"\x1dmin_pollution_to_damage_trees\x18\a \x01(\x05R\x19minPollutionToDamageTrees\x12F\n" +
	" pollution_with_max_forest_damage\x18\b \x01(\x05R\x1cpollutionWithMaxForestDamage\x129\n" +
	"\x19pollution_per_tree_damage\x18\t \x01(\x05R\x16pollutionPerTreeDamage\x12J\n" +
	"\"pollution_restored_per_tree_damage\x18\n" +
	" \x01(\x05R\x1epollutionRestoredPerTreeDamage\x12B\n" +
	"\x1emax_pollution_to_restore_trees\x18\v \x01(\x05R\x1amaxPollutionToRestoreTrees\x12\\\n" +
	"+enemy_attack_pollution_consumption_modifier\x18\f \x01(\x05R'enemyAttackPollutionConsumptionModifier\"\xa5\x01\n" +
	"\x16FactorioEnemyEvolution\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vtime_factor\x18\x02 \x01(\x01R\n" +
	"timeFactor\x12%\n" +
	"\x0edestroy_factor\x18\x03 \x01(\x01R\rdestroyFactor\x12)\n" +
	"\x10pollution_factor\x18\x04 \x01(\x01R\x0fpollutionFactor\"\x8f\x06\n" +
	"\x16FactorioEnemyExpansion\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x124\n" +
	"\x16max_expansion_distance\x18\x02 \x01(\x05R\x14maxExpansionDistance\x12C\n" +
	"\x1efriendly_base_influence_radius\x18\x03 \x01(\x05R\x1bfriendlyBaseInfluenceRadius\x12E\n" +
	"\x1fenemy_building_influence_radius\x18\x04 \x01(\x05R\x1cenemyBuildingInfluenceRadius\x121\n" +
	"\x14building_coefficient\x18\x05 \x01(\x01R\x13buildingCoefficient\x124\n" +
	"\x16other_base_coefficient\x18\x06 \x01(\x01R\x14otherBaseCoefficient\x12D\n" +
	"\x1eneighbouring_chunk_coefficient\x18\a \x01(\x01R\x1cneighbouringChunkCoefficient\x12M\n" +
	"#neighbouring_base_chunk_coefficient\x18\b \x01(\x01R neighbouringBaseChunkCoefficient\x12E\n" +
	"\x1fmax_colliding_tiles_coefficient\x18\t \x01(\x01R\x1cmaxCollidingTilesCoefficient\x123\n" +
	"\x16settler_group_min_size\x18\n" +
	" \x01(\x05R\x13settlerGroupMinSize\x123\n" +
	"\x16settler_group_max_size\x18\v \x01(\x05R\x13settlerGroupMaxSize\x124\n" +
	"\x16min_expansion_cooldown\x18\f \x01(\x05R\x14minExpansionCooldown\x124\n" +
	"\x16max_expansion_cooldown\x18\r \x01(\x05R\x14maxExpansionCooldown\"\x93\x06\n" +
	"\x11FactorioUnitGroup\x127\n" +
	"\x18min_group_gathering_time\x18\x01 \x01(\x05R\x15minGroupGatheringTime\x127\n" +
	"\x18max_group_gathering_time\x18\x02 \x01(\x05R\x15maxGroupGatheringTime\x12A\n" +
	"\x1emax_wait_time_for_late_members\x18\x03 \x01(\x05R\x19maxWaitTimeForLateMembers\x12(\n" +
	"\x10max_group_radius\x18\x04 \x01(\x01R\x0emaxGroupRadius\x12(\n" +
	"\x10min_group_radius\x18\x05 \x01(\x01R\x0eminGroupRadius\x12B\n" +
	"\x1emax_member_speedup_when_behind\x18\x06 \x01(\x01R\x1amaxMemberSpeedupWhenBehind\x12B\n" +
	"\x1emax_member_slowdown_when_ahead\x18\a \x01(\x01R\x1amaxMemberSlowdownWhenAhead\x129\n" +
	"\x19max_group_slowdown_factor\x18\b \x01(\x01R\x16maxGroupSlowdownFactor\x12F\n" +
	" max_group_member_fallback_factor\x18\t \x01(\x05R\x1cmaxGroupMemberFallbackFactor\x124\n" +
	"\x16member_disown_distance\x18\n" +
	" \x01(\x05R\x14memberDisownDistance\x12J\n" +
	"\"tick_tolerance_when_member_arrives\x18\v \x01(\x05R\x1etickToleranceWhenMemberArrives\x129\n" +
	"\x19max_gathering_unit_groups\x18\f \x01(\x05R\x16maxGatheringUnitGroups\x12-\n" +
	"\x13max_unit_group_size\x18\r \x01(\x05R\x10maxUnitGroupSize\"\xe8\x02\n" +
	"\x13FactorioMapSettings\x12P\n" +
	"\x13difficulty_settings\x18\x01 \x01(\v2\x1f.api.FactorioDifficultySettingsR\x12difficultySettings\x12<\n" +
	"\tpollution\x18\x02 \x01(\v2\x1e.api.FactorioPollutionSettingsR\tpollution\x12D\n" +
	"\x0fenemy_evolution\x18\x03 \x01(\v2\x1b.api.FactorioEnemyEvolutionR\x0eenemyEvolution\x12D\n" +
	"\x0fenemy_expansion\x18\x04 \x01(\v2\x1b.api.FactorioEnemyExpansionR\x0eenemyExpansion\x125\n" +
	"\n" +
	"unit_group\x18\x05 \x01(\v2\x16.api.FactorioUnitGroupR\tunitGroup\"h\n" +
	"\x18FactorioResourceSettings\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\x02R\tfrequency\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x02R\x04size\x12\x1a\n" +
	"\brichness\x18\x03 \x01(\x02R\brichness\"\xad\x01\n" +
	"\x15FactorioCliffSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x11cliff_elevation_0\x18\x02 \x01(\x05R\x0fcliffElevation0\x128\n" +
	"\x18cliff_elevation_interval\x18\x03 \x01(\x05R\x16cliffElevationInterval\x12\x1a\n" +
	"\brichness\x18\x04 \x01(\x05R\brichness\"\xaf\x03\n" +
	"\x16FactorioMapGenSettings\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12#\n" +
	"\rstarting_area\x18\x03 \x01(\x05R\fstartingArea\x12#\n" +
	"\rpeaceful_mode\x18\x04 \x01(\bR\fpeacefulMode\x12a\n" +
	"\x12autoplace_controls\x18\x05 \x03(\v22.api.FactorioMapGenSettings.AutoplaceControlsEntryR\x11autoplaceControls\x12A\n" +
	"\x0ecliff_settings\x18\x06 \x01(\v2\x1a.api.FactorioCliffSettingsR\rcliffSettings\x12\x12\n" +
	"\x04seed\x18\a \x01(\x05R\x04seed\x1ac\n" +
	"\x16AutoplaceControlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.api.FactorioResourceSettingsR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x0eFactorioConfig\x12#\n" +
	"\x04base\x18\x01 \x01(\v2\x0f.api.BaseConfigR\x04base\x123\n" +
	"\x06server\x18\x02 \x01(\v2\x1b.api.FactorioServerSettingsR\x06server\x12*\n" +
	"\x03map\x18\x03 \x01(\v2\x18.api.FactorioMapSettingsR\x03map\x124\n" +
	"\amap_gen\x18\x04 \x01(\v2\x1b.api.FactorioMapGenSettingsR\x06mapGen\"\x82\x02\n" +
	"\x0fMinecraftConfig\x12#\n" +
	"\x04base\x18\x01 \x01(\v2\x0f.api.BaseConfigR\x04base\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\x12\x1b\n" +
	"\trcon_port\x18\x03 \x01(\rR\brconPort\x122\n" +
	"\bgamemode\x18\x04 \x01(\x0e2\x16.api.MinecraftGamemodeR\bgamemode\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x12\x1f\n" +
	"\vmax_players\x18\x06 \x01(\rR\n" +
	"maxPlayers\x12#\n" +
	"\rview_distance\x18\a \x01(\x05R\fviewDistance\"&\n" +
	"\x14GetConfigByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x15GetConfigByIdResponse\x129\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x13.api.FactorioConfigR\rconfiguration\"\x1d\n" +
	"\x1bGetAllConfigurationsRequest\"[\n" +
	"\x1cGetAllConfigurationsResponse\x12;\n" +
	"\x0econfigurations\x18\x01 \x03(\v2\x13.api.FactorioConfigR\x0econfigurations\"U\n" +
	"\x18PostConfigurationRequest\x129\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x13.api.FactorioConfigR\rconfiguration\"\x1b\n" +
	"\x19PostConfigurationResponse\"d\n" +
	"\x17PutConfigurationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\rconfiguration\x18\x02 \x01(\v2\x13.api.FactorioConfigR\rconfiguration\"\x1a\n" +
	"\x18PutConfigurationResponse\",\n" +
	"\x1aDeleteConfigurationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\x1bDeleteConfigurationResponse*z\n" +
	"\x11ConfigurationType\x12\"\n" +
	"\x1eCONFIGURATION_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONFIGURATION_TYPE_FACTORIO\x10\x01\x12 \n" +
	"\x1cCONFIGURATION_TYPE_MINECRAFT\x10\x02*\xbd\x01\n" +
	"\x11MinecraftGamemode\x12\"\n" +
	"\x1eMINECRAFT_GAMEMODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bMINECRAFT_GAMEMODE_SURVIVAL\x10\x01\x12\x1f\n" +
	"\x1bMINECRAFT_GAMEMODE_CREATIVE\x10\x02\x12 \n" +
	"\x1cMINECRAFT_GAMEMODE_ADVENTURE\x10\x03\x12 \n" +
	"\x1cMINECRAFT_GAMEMODE_SPECTATOR\x10\x042\xff\x02\n" +
	"\x14ConfigurationService\x12@\n" +
	"\aGetById\x12\x19.api.GetConfigByIdRequest\x1a\x1a.api.GetConfigByIdResponse\x12M\n" +
	"\x06GetAll\x12 .api.GetAllConfigurationsRequest\x1a!.api.GetAllConfigurationsResponse\x12E\n" +
	"\x04Post\x12\x1d.api.PostConfigurationRequest\x1a\x1e.api.PostConfigurationResponse\x12B\n" +
	"\x03Put\x12\x1c.api.PutConfigurationRequest\x1a\x1d.api.PutConfigurationResponse\x12K\n" +
	"\x06Delete\x12\x1f.api.DeleteConfigurationRequest\x1a .api.DeleteConfigurationResponseB/Z-github.com/vv-sam/otus-project/proto/grpc/apib\x06proto3"

var (
	file_configuration_proto_rawDescOnce sync.Once
	file_configuration_proto_rawDescData []byte
)

func file_configuration_proto_rawDescGZIP() []byte {
	file_configuration_proto_rawDescOnce.Do(func() {
		file_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)))
	})
	return file_configuration_proto_rawDescData
}

var file_configuration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_configuration_proto_goTypes = []any{
	(ConfigurationType)(0),               // 0: api.ConfigurationType
	(MinecraftGamemode)(0),               // 1: api.MinecraftGamemode
	(*BaseConfig)(nil),                   // 2: api.BaseConfig
	(*FactorioServerSettings)(nil),       // 3: api.FactorioServerSettings
	(*FactorioDifficultySettings)(nil),   // 4: api.FactorioDifficultySettings
	(*FactorioPollutionSettings)(nil),    // 5: api.FactorioPollutionSettings
	(*FactorioEnemyEvolution)(nil),       // 6: api.FactorioEnemyEvolution
	(*FactorioEnemyExpansion)(nil),       // 7: api.FactorioEnemyExpansion
	(*FactorioUnitGroup)(nil),            // 8: api.FactorioUnitGroup
	(*FactorioMapSettings)(nil),          // 9: api.FactorioMapSettings
	(*FactorioResourceSettings)(nil),     // 10: api.FactorioResourceSettings
	(*FactorioCliffSettings)(nil),        // 11: api.FactorioCliffSettings
	(*FactorioMapGenSettings)(nil),       // 12: api.FactorioMapGenSettings
	(*FactorioConfig)(nil),               // 13: api.FactorioConfig
	(*MinecraftConfig)(nil),              // 14: api.MinecraftConfig
	(*GetConfigByIdRequest)(nil),         // 15: api.GetConfigByIdRequest
	(*GetConfigByIdResponse)(nil),        // 16: api.GetConfigByIdResponse
	(*GetAllConfigurationsRequest)(nil),  // 17: api.GetAllConfigurationsRequest
	(*GetAllConfigurationsResponse)(nil), // 18: api.GetAllConfigurationsResponse
	(*PostConfigurationRequest)(nil),     // 19: api.PostConfigurationRequest
	(*PostConfigurationResponse)(nil),    // 20: api.PostConfigurationResponse
	(*PutConfigurationRequest)(nil),      // 21: api.PutConfigurationRequest
	(*PutConfigurationResponse)(nil),     // 22: api.PutConfigurationResponse
	(*DeleteConfigurationRequest)(nil),   // 23: api.DeleteConfigurationRequest
	(*DeleteConfigurationResponse)(nil),  // 24: api.DeleteConfigurationResponse
	nil,                                  // 25: api.FactorioMapGenSettings.AutoplaceControlsEntry
}
var file_configuration_proto_depIdxs = []int32{
	0,  // 0: api.BaseConfig.type:type_name -> api.ConfigurationType
	4,  // 1: api.FactorioMapSettings.difficulty_settings:type_name -> api.FactorioDifficultySettings
	5,  // 2: api.FactorioMapSettings.pollution:type_name -> api.FactorioPollutionSettings
	6,  // 3: api.FactorioMapSettings.enemy_evolution:type_name -> api.FactorioEnemyEvolution
	7,  // 4: api.FactorioMapSettings.enemy_expansion:type_name -> api.FactorioEnemyExpansion
	8,  // 5: api.FactorioMapSettings.unit_group:type_name -> api.FactorioUnitGroup
	25, // 6: api.FactorioMapGenSettings.autoplace_controls:type_name -> api.FactorioMapGenSettings.AutoplaceControlsEntry
	11, // 7: api.FactorioMapGenSettings.cliff_settings:type_name -> api.FactorioCliffSettings
	2,  // 8: api.FactorioConfig.base:type_name -> api.BaseConfig
	3,  // 9: api.FactorioConfig.server:type_name -> api.FactorioServerSettings
	9,  // 10: api.FactorioConfig.map:type_name -> api.FactorioMapSettings
	12, // 11: api.FactorioConfig.map_gen:type_name -> api.FactorioMapGenSettings
	2,  // 12: api.MinecraftConfig.base:type_name -> api.BaseConfig
	1,  // 13: api.MinecraftConfig.gamemode:type_name -> api.MinecraftGamemode
	13, // 14: api.GetConfigByIdResponse.configuration:type_name -> api.FactorioConfig
	13, // 15: api.GetAllConfigurationsResponse.configurations:type_name -> api.FactorioConfig
	13, // 16: api.PostConfigurationRequest.configuration:type_name -> api.FactorioConfig
	13, // 17: api.PutConfigurationRequest.configuration:type_name -> api.FactorioConfig
	10, // 18: api.FactorioMapGenSettings.AutoplaceControlsEntry.value:type_name -> api.FactorioResourceSettings
	15, // 19: api.ConfigurationService.GetById:input_type -> api.GetConfigByIdRequest
	17, // 20: api.ConfigurationService.GetAll:input_type -> api.GetAllConfigurationsRequest
	19, // 21: api.ConfigurationService.Post:input_type -> api.PostConfigurationRequest
	21, // 22: api.ConfigurationService.Put:input_type -> api.PutConfigurationRequest
	23, // 23: api.ConfigurationService.Delete:input_type -> api.DeleteConfigurationRequest
	16, // 24: api.ConfigurationService.GetById:output_type -> api.GetConfigByIdResponse
	18, // 25: api.ConfigurationService.GetAll:output_type -> api.GetAllConfigurationsResponse
	20, // 26: api.ConfigurationService.Post:output_type -> api.PostConfigurationResponse
	22, // 27: api.ConfigurationService.Put:output_type -> api.PutConfigurationResponse
	24, // 28: api.ConfigurationService.Delete:output_type -> api.DeleteConfigurationResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_configuration_proto_init() }
func file_configuration_proto_init() {
	if File_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configuration_proto_goTypes,
		DependencyIndexes: file_configuration_proto_depIdxs,
		EnumInfos:         file_configuration_proto_enumTypes,
		MessageInfos:      file_configuration_proto_msgTypes,
	}.Build()
	File_configuration_proto = out.File
	file_configuration_proto_goTypes = nil
	file_configuration_proto_depIdxs = nil
}
